eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${vcap.services.eureka-service.credentials.uri:http://localhost:8761}/eureka/

---

spring:
    profiles: localdb
    datasource:
        url: jdbc:mysql://localhost/rr_ws
        username: root
        password: 
